### ISSUE TITLE
Exception (random?)

### ISSUE THREAD

**Issue by brugnara** [singlow/meteor-live-maps#7]
I'm getting this exception, any hints?

```js
Exception in queued task: Error
    at Error (native)
    at new nf (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:22:629)
    at of (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:22:742)
    at kh.setMap (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:27:1260)
    at kh.N.setValues (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:20:84)
    at kh.ah (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:33:2561)
    at new kh (https://maps.gstatic.com/maps-api-v3/api/js/19/7a/main.js:36:546)
    at Object.addMarker [as added] (http://local.host:3000/packages/mrt_live-maps.js?bdfb87f877b4ac1061a10420061486899f0d32e3:89:14)
    at LocalCollection._observeFromObserveChanges.observeChangesCallbacks.added (http://local.host:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3897:28)
    at Object.LocalCollection._CachingChangeObserver.self.applyChange.added (http://local.host:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3797:44)
```

**Comment by doubletaketech** [comment]
I'm seeing this too. Any solution?

**Comment by doubletaketech** [comment]
Is this issue being looked into it? This is a showstopper for me using this package because it all of sudden just stopped working and throwing these errors for every marker

```
Exception in queued task: Error
    at Error (native)
    at new rf (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:23:683)
    at sf (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:23:796)
    at Oh.setTitle (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:28:1260)
    at Oh.O.setValues (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:21:84)
    at Oh.Dh (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:35:2561)
    at new Oh (http://maps.gstatic.com/maps-api-v3/api/js/20/2/intl/en_gb/main.js:38:546)
    at Object.addMarker [as added] (http://localhost:3000/packages/mrt_live-maps.js?bdfb87f877b4ac1061a10420061486899f0d32e3:89:14)
    at LocalCollection._observeFromObserveChanges.observeChangesCallbacks.added (http://localhost:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3897:28)
    at Object.LocalCollection._CachingChangeObserver.self.applyChange.added (http://localhost:3000/packages/minimongo.js?e8806aa7782b729b2517ebc0cd10b321667f1427:3797:44)
```

**Comment by doubletaketech** [comment]
Note: I think this package assumes autopublish is on.  It only started these errors when I switch to subscriptions.  Data is getting to the markers from the subscription.

**Comment by sandelld** [comment]
any update on this? I'm getting the same thing ...

**Comment by singlow** [comment]
I just got back into this project and re-tested it. I am not having the issue you described. If you disable auto-publish, you will need to have a subscription for the data in your collection that you want to appear, same as you would for any other template view.
